version: '3.8'

x-service: &service
  logging:
    driver: json-file
    options:
      max-size: "100m"
      max-file: "2"
  restart: unless-stopped

x-service-deploy: &service-deploy
  mode: replicated
  replicas: 1
  placement:
    constraints:
      - node.role == manager

services:
  # https://sysadmins.co.za/setup-a-nfs-server-with-docker/
  nfs:
    container_name: nfs
    image: itsthenetwork/nfs-server-alpine:12
    ports:
      - 2049:2049
    deploy:
      <<: *service-deploy
    <<: *service
    environment:
      SHARED_DIRECTORY: ${DATAPATH?Variable DATAPATH not set}
      PERMITTED: ${MASTER_IP_MASK?Variable MASTER_IP_MASK not set}
    volumes:
      - ${DATAPATH?Variable DATAPATH not set}/nfs:${DATAPATH?Variable DATAPATH not set}
    privileged: true
    #cap_add:
      #- SYS_ADMIN
      #- SETPCAP
      #- NET_ADMIN
      #- SYS_TIME
    entrypoint: /usr/bin/nfsd.sh

  # https://doc.traefik.io/traefik/getting-started/quick-start/
  # https://dockerswarm.rocks/traefik/
  traefik:
    container_name: traefik
    image: traefik:v2.6
    ports:
      - 80:80
      - 443:443
    deploy:
      <<: *service-deploy
      labels:
        - traefik.enable=true
        - traefik.docker.network=ingress
        - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable USERNAME not set}:${HASHED_PASSWORD?Variable HASHED_PASSWORD not set}
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik-api-http.rule=Host(`traefik.${DOMAIN?Variable DOMAIN not set}`)
        - traefik.http.routers.traefik-api-http.entrypoints=http
        - traefik.http.routers.traefik-api-http.service=api@internal
        #- traefik.http.routers.traefik-api-http.middlewares=https-redirect
        - traefik.http.routers.traefik-api-http.middlewares=admin-auth
        - traefik.http.routers.traefik-api-https.rule=Host(`traefik.${DOMAIN?Variable DOMAIN not set}`)
        - traefik.http.routers.traefik-api-https.entrypoints=https
        - traefik.http.routers.traefik-api-https.tls=true
        - traefik.http.routers.traefik-api-https.service=api@internal
        - traefik.http.routers.traefik-api-https.tls.certresolver=le
        - traefik.http.routers.traefik-api-https.middlewares=admin-auth
        - traefik.http.services.traefik.loadbalancer.server.port=8080
    <<: *service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --providers.docker.defaultRule=Host(`{{ .Name }}.${DOMAIN?Variable DOMAIN not set}`)
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=${EMAIL?Variable EMAIL not set}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
      - --api.dashboard=true
    networks:
      - ingress
      - database
      - monitoring
      - bitwarden
      - gitlab
      - registry
      - minio
      - nocodb
      - openproject
      - portainer

x-volume: &volume
  driver: local
x-volume-driver-opts: &volume-driver-opts
  type: nfs
  o: nfsvers=4,rw

volumes:
  traefik-certs:
    name: traefik-certs
    <<: *volume
    driver_opts:
      <<: *volume-driver-opts
      device: "${MASTER_IP?Variable MASTER_IP not set}:${DATAPATH?Variable DATAPATH not set}/traefik/certificates"
  portainer-data:
    name: portainer-data
    <<: *volume
    driver_opts:
      <<: *volume-driver-opts
      device: "${MASTER_IP?Variable MASTER_IP not set}:${DATAPATH?Variable DATAPATH not set}/portainer/data"
  registry-data:
    name: registry-data
    <<: *volume
    driver_opts:
      <<: *volume-driver-opts
      device: "${MASTER_IP?Variable MASTER_IP not set}:${DATAPATH?Variable DATAPATH not set}/registry/data"
  minio-data:
    name: minio-data
    <<: *volume
    driver_opts:
      <<: *volume-driver-opts
      device: "${MASTER_IP?Variable MASTER_IP not set}:${DATAPATH?Variable DATAPATH not set}/minio/data"

x-network: &network
  driver: overlay
  attachable: true

networks:
  ingress:
    name: ingress
    <<: *network
  monitoring:
    name: monitoring
    <<: *network
  bitwarden:
    name: bitwarden
    <<: *network
  gitlab:
    name: gitlab
    <<: *network
  registry:
    name: registry
    <<: *network
  minio:
    name: minio
    <<: *network
  database:
    name: database
    <<: *network
  nocodb:
    name: nocodb
    <<: *network
  openproject:
    name: openproject
    <<: *network
  portainer:
    name: portainer
    <<: *network
