global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'telegraf'
    dns_sd_configs:
      - refresh_interval: 15s
        type: 'A'
        port: 9273
        names:
          - telegraf-node
          - telegraf
          - tasks.telegraf-node
          - tasks.telegraf

alerting:
  alertmanagers:
    - scheme: http
      dns_sd_configs:
      - refresh_interval: 5s
        #port: 80
        names:
          - alertmanager
